# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fitness +' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fitness +
	pod 'Firebase/Database'
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'SwiftyGif'
	pod 'Charts'
	pod 'GoogleSignIn'
	pod 'FBSDKLoginKit'
end
